{
 "title": "FastAPI SRE Dashboard",
 "tags": [
  "fastapi",
  "sre",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "FastAPI Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "FastAPI p95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_highr_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "FastAPI 5xx Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status=\"5xx\"}[5m]))"
    }
   ]
  },
  {
   "title": "CPU by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"fastapi\",container=\"fastapi-sre-lab\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"fastapi\",container=\"fastapi-sre-lab\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FastAPI HPA Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"fastapi\",horizontalpodautoscaler=\"fastapi-sre-lab\"}"
    }
   ]
  }
 ]
}